Error: Not in a Firebase app directory (could not locate firebase.json)
 *  The terminal process "bash '-c', 'npm run start'" terminated with exit code: 1.
 *  Terminal will be reused by tasks, press any key to close it.

 *  Executing task: (set -o pipefail && npm stop 2>&1 | tee /tmp/ai.1.log)

npm error Missing script: "stop"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: /home/.npm/_logs/2025-06-02T22_32_09_936Z-debug-0.log

 *  The terminal process "bash '-c', '(set -o pipefail && npm stop 2>&1 | tee /tmp/ai.1.log)'" terminated with exit code: 1.
 *  Terminal will be reused by tasks, press any key to close it.